name: Discord Notification

on: [push,pull_request,fork]

jobs:
  report-status:

    runs-on: ubuntu-latest

    steps:
      - name: Run Discord Webhook
        uses: baked-libs/discord-webhook@main
        with:
          id: ${{ secrets.DISCORD_NOTIFICATION_ID }}
          token: ${{ secrets.DISCORD_NOTIFICATION_TOKEN }}
