name: Push To Repo

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 1 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Build with Maven
      run: mvn package --file pom.xml
    - name: Nexus Repo Publish
      uses: sonatype-nexus-community/nexus-repo-github-action@master
      with:
        serverUrl: https://repo.thedutchruben.nl/
        username: admin
        password: ${{ secrets.SONAR_TOKEN }}
        format: maven2
        repository: maven-releases
        coordinates: groupId=nl.thedutchruben artifactId=mccore version=${{ steps.project.outputs.version }}
        assets: extension=jar
        filename: ./target/mccore-${{ steps.project.outputs.version }}.jar
